version: '3'

services:
    app:
        build:
            context: .
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - laravel
        extra_hosts:
            - "host.docker.internal:host-gateway"

    webserver:
        image: arm64v8/nginx
        container_name: nginx-server
        restart: unless-stopped
        ports:
            - "8888:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    mysql:
        image: mysql/mysql-server:latest-aarch64
        container_name: mysql
        tty: true
        ports:
            - "3333:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: dancer
            MYSQL_PASSWORD: dancer
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_HOST: ${DB_HOST}
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        restart: always
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
